### ISSUE TITLE
LinterJsxhint.Linter is deprecated.

### ISSUE THREAD

**Issue by ccorcos** [AtomLinter/linter-jsxhint#23] opened 2015-07-12 19:32 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterJsxhint.Linter (/Users/chet/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterJsxhint (/Users/chet/.atom/packages/linter-jsxhint/lib/linter-jsxhint.coffee:24:4)
Object.lint (/Users/chet/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/chet/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/chet/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/chet/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by Arcanemagus** [comment] 2016-02-01 21:19
Marking as a duplicate of #21.

**Closed by Arcanemagus** 2016-02-01 21:19 UTC
