### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by hershmire** [AtomLinter/linter-jsxhint#22] opened 2015-07-08 17:40 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (/Users/eddie/.dotfiles/atom.symlink/packages/linter/lib/main.coffee:57:8)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
```

**Comment by q13** [comment] 2015-07-20 08:50
+1

**Comment by ApfelUser** [comment] 2015-07-21 15:57
:+1:

**Comment by mnlfischer** [comment] 2015-07-27 12:58
+1

**Comment by svenhornberg** [comment] 2015-07-29 18:58
:+1:

**Comment by Arcanemagus** [comment] 2016-02-01 21:19
Marking as a duplicate of #21.

**Closed by Arcanemagus** 2016-02-01 21:19 UTC
